name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: auto-deploy-test
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 16.20.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.20.0

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        # run_install: false

    - run: pnpm install

    - name: build project
      run: pnpm run build-only

    # - name: Deploy to Server
    #   uses: easingthemes/ssh-deploy@main
    #   env:
    #       SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
    #       ARGS: "-rltgoDzvO --delete"
    #       SOURCE: "dist/"
    #       REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #       REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #       TARGET: ${{ secrets.REMOTE_TARGET }}
    #       EXCLUDE: "/node_modules/"