
  name: Docker image build and push
  on: [push]
  jobs: 
    Docker-Build-Push:
      runs-on: ubuntu-latest
      steps: 
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: docker image build
          uses: docker build -t lvqihang/fronted:latest
        - name: list docker images
          uses: docker image ls